# Generated by Django 3.1.1 on 2020-09-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_userid', models.CharField(default='', max_length=50)),
                ('s_age', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
